---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu
    tags: apache,apache2,ubuntu,php
    apt:
      name:
        -  apache2
        -  libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: install httpd and php packages for CentOS
    tags: httpd,php,apache
    dnf:
      name: 
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"
  
   
