- name: install mariadb package centos
  tags: mariadb,centos,db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package ubuntu
  tags: mariadb,ubuntu,db
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

