- name: install unzip
  tags: unzip
  package:
    name: unzip

- name: install terraform
  tags: terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.13.2/terraform_0.13.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0775
